-- BANETO EXPORT FOR: delete items!
BANETO_AddItemToDeleteList([[Nozdorite]])
BANETO_AddItemToDeleteList([[Neltharite]])
BANETO_AddItemToDeleteList([[Bruffalon Flank]])
BANETO_AddItemToDeleteList([[Maybe Meat]])
BANETO_AddItemToDeleteList([[Malygite]])
BANETO_AddItemToDeleteList([[Alexstraszite]])
BANETO_AddItemToDeleteList([[Eternity Amber]])
BANETO_AddItemToDeleteList([[Sundered Onyx]])
BANETO_AddItemToDeleteList([[Vibrant Emerald]])
BANETO_AddItemToDeleteList([[Mystic Sapphire]])
BANETO_AddItemToDeleteList([[Queen's Ruby]])
BANETO_AddItemToDeleteList([[Exceptional Pelt]])
BANETO_AddItemToDeleteList([[Burly Bear Haunch]])
BANETO_AddItemToDeleteList([[Wildercloth]])
BANETO_AddItemToDeleteList([[Tattered Wildercloth]])
BANETO_AddItemToDeleteList([[Ysemerald]])
BANETO_AddItemToDeleteList([[High-Fiber Leaf]])
BANETO_AddItemToDeleteList([[Woolly Mountain Pelt]])
BANETO_AddItemToDeleteList([[Primal Bear Spine]])
BANETO_AddItemToDeleteList([[Causality Band]])
BANETO_AddItemToDeleteList([[Springrain Ring of Destruction]])
BANETO_AddItemToDeleteList([[Springrain Stone of Destruction]])
BANETO_AddItemToDeleteList([[Springrain Idol of Destruction]])
BANETO_AddItemToDeleteList([[Springrain Medallion]])
BANETO_AddItemToDeleteList([[Thunderscale Legguards]])
BANETO_AddItemToDeleteList([[Drake Race Starting Rifle]])
BANETO_AddItemToDeleteList([[Isle Trapper's Dagger]])
BANETO_AddItemToDeleteList([[Mighty Mammoth Ribs]])
BANETO_AddItemToDeleteList([[Fluorescent Fluid]])
BANETO_AddItemToDeleteList([[Mastodon Tusk]])
BANETO_AddItemToDeleteList([[Primal Ritual Shell]])
BANETO_AddItemToDeleteList([[Large Sturdy Femur]])
BANETO_AddItemToDeleteList([[Tuskarr Jerky]])
BANETO_AddItemToDeleteList([[Stonewatcher's Toe]])
BANETO_AddItemToDeleteList([[Lava Beetle]])
BANETO_AddItemToDeleteList([[Snowball]])
BANETO_AddItemToDeleteList([[Salt Deposit]])
BANETO_AddItemToDeleteList([[Small Rumble Purse]])
BANETO_AddItemToDeleteList([[Bobby Carlisle's Thinking Cap Notes]])
BANETO_AddItemToDeleteList([[Preservationist's Dispatch Two]])
BANETO_AddItemToDeleteList([[Warcraft Rumble Welcome Letter]])
BANETO_AddItemToDeleteList([[Dreamsurge Coalescence]])
BANETO_AddItemToDeleteList([[Hornstrider's Crossbow of the Quickblade]])
BANETO_AddItemToDeleteList([[Recipe: Thrice-Spiced Mammoth Kabob]])